FORMAT: 1A


# Demo Onboarding Process

This is the process for downloading the demo on your device

## 1. Download the app from our portals

This needs to be done on your device
- For the **Jiff demo**, go to [jiff-master.surge.sh](jiff-master.surge.sh) to download the app:
![image](https://dl.dropboxusercontent.com/s/qqbpeqnmapzx590/jiff.png?dl=0)
- For the **Castlight Complete demo**, go to [castlight-master.surge.sh](castlight-master.surge.sh) to download the app:
![image](https://dl.dropboxusercontent.com/s/k3myj0gutfafywm/castlight.png?dl=0)


## 2. Trust the Jiff, Inc. certificate

If you try to start the app the very first time it will prompt you:

![image](http://castlight.surge.sh/cdn/trust.png)

Follow these steps:

- Go to Settings > General > Profiles & Device Management
- Click on Jiff, Inc.:
![image](http://castlight.surge.sh/cdn/certificate.png)
- Click on Trust "Jiff, Inc." and tap on Trust:
![image](http://castlight.surge.sh/cdn/trust2.png)
 

## 3. Launch the experience

- Tap on the email icon
- Select a persona:
![image](http://castlight.surge.sh/cdn/exp.png)
- Then Tap on the Activate button. No password is required.
