FORMAT: 1A


# Demo Onboarding Process

This is the process for downloading the demo on your device

## 1. Accept the Crashlytics invite

This needs to be done on your device
- For the Jiff demo:
![image](http://castlight.surge.sh/cdn/jiff.png)
- For the Castlight Complete demo:
![image](http://castlight.surge.sh/cdn/castlight.png)

### If you did not receive the invite:

- Go to https://castlighthealth.okta.com/app/UserHome
- Click on Mimecast Personal Portal
- Find the Crashlytics email and click on:
![image](http://castlight.surge.sh/cdn/permit.png)

## 2. Install the app

![image](http://castlight.surge.sh/cdn/install.png)

## 3. Trust the Jiff, Inc. certificate

If you try to start the app the very first time it will prompt you:

![image](http://castlight.surge.sh/cdn/trust.png)

Follow these steps:

- Go to Settings > General > Profiles & Device Management
- Click on Jiff, Inc.:
![image](http://castlight.surge.sh/cdn/certificate.png)
- Click on Trust "Jiff, Inc." and tap on Trust:
![image](http://castlight.surge.sh/cdn/trust2.png)
 

## 4. Launch the experience

- Tap on the email icon
- Select a persona:
![image](http://castlight.surge.sh/cdn/exp.png)
- Then Tap on the Activate button. No password is required.

## 5. Install updates

### From the email (option 1):
![image](http://castlight.surge.sh/cdn/email.png)
### From the Beta app (option2):
- Tap on Beta
![image](http://castlight.surge.sh/cdn/beta1.png)
- Select Jiff Demo v1
![image](http://castlight.surge.sh/cdn/beta2.png)